In [ ]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('OSCA Category Descriptions.xlsx', sheet_name='Table 1', skiprows=4)    
df.head()

,Identifier,Principal Title,Alternative Title,Lead Statement,Registration or Licensing,Inclusion and Exclusion Statements,Skill Attributes,Skill Level,Main Tasks,Specialisations,Occupation in NEC category
0,111131,Corporate Services Manager,Business Services Manager,"Plans, organises, directs, controls and coordi...",NaN,NaN,NaN,1.0,"Provides high level administrative, strategic ...",NaN,NaN
1,111231,Finance Manager,Chief Financial Officer; Finance Director; Fin...,"Plans, organises, directs, controls and coordi...",NaN,NaN,NaN,1.0,"Determines, implements, monitors, reviews and ...",Financial Administrator,NaN
2,111331,Human Resources Manager,HR Manager; People and Culture Manager,"Plans, organises, directs, controls and coordi...",NaN,NaN,NaN,1.0,"Determines, implements, monitors, reviews and ...",Employee Relations Manager; Training and Devel...,NaN
3,111431,Policy and Planning Manager,Public Policy Manager,"Plans, organises, directs, controls and coordi...",NaN,NaN,NaN,1.0,"Develops, implements and monitors strategic an...",Strategic Planning Manager,NaN
4,111531,Research and Development Manager,R & D Manager,"Plans, organises, directs, controls and coordi...",NaN,NaN,NaN,1.0,Develops and implements research project strat...,NaN,NaN

In [3]:
df.shape

(1157, 11)

In [4]:
# Concatenate Principal Title and Alternative Title
df['OCSA TItle'] = df['Principal Title'].astype(str) + ' , ' + df['Alternative Title'].astype(str)

In [5]:
# Remove all columns except 'OCSA Code' and 'OCSA Title'
df = df[['Identifier', 'OCSA TItle', 'Principal Title','Alternative Title', 'Lead Statement','Main Tasks','Specialisations']]
df.head()

,Identifier,OCSA TItle,Principal Title,Alternative Title,Lead Statement,Main Tasks,Specialisations
0,111131,"Corporate Services Manager , Business Services...",Corporate Services Manager,Business Services Manager,"Plans, organises, directs, controls and coordi...","Provides high level administrative, strategic ...",NaN
1,111231,"Finance Manager , Chief Financial Officer; Fin...",Finance Manager,Chief Financial Officer; Finance Director; Fin...,"Plans, organises, directs, controls and coordi...","Determines, implements, monitors, reviews and ...",Financial Administrator
2,111331,"Human Resources Manager , HR Manager; People a...",Human Resources Manager,HR Manager; People and Culture Manager,"Plans, organises, directs, controls and coordi...","Determines, implements, monitors, reviews and ...",Employee Relations Manager; Training and Devel...
3,111431,"Policy and Planning Manager , Public Policy Ma...",Policy and Planning Manager,Public Policy Manager,"Plans, organises, directs, controls and coordi...","Develops, implements and monitors strategic an...",Strategic Planning Manager
4,111531,"Research and Development Manager , R & D Manager",Research and Development Manager,R & D Manager,"Plans, organises, directs, controls and coordi...",Develops and implements research project strat...,NaN

In [6]:
# export to parquet
df['Identifier'] = df['Identifier'].astype(str)
df.to_parquet('OSCA_Category_Descriptions.parquet', index=False)